POST https://bwhst.brainhoney.com/Editor/UpdateContent.ashx

Cookie: <COOKIE>

groupid:~
title:Test Assn
abbreviation:
content:<div>&nbsp;</div>
itemhref:
issco:false
scoreview:false
issite:false
isblti:false
selectedhref:
selectedtext:
isbrokenlink:false
customfields:
flagedit:false
comments:
attachments:/Resource/14915878,0/Assets%2FREADME.md?attachment=1,README.md,Assets%2FREADME.md,
priority:
password:
duedate:
hasduedate:false
visiblefromdate:
hasvisiblefromdate:false
resultsvisibledate:
hasresultsvisibledate:false
mindate:Thu Sep 05 2013 00:00:00 GMT-0400 (EDT)
maxdate:Sat Sep 06 2014 00:00:00 GMT-0400 (EDT)
duedategrace:-1
allowlate:true
duedategraceunit:nolimit
duedategraceval:-1
gradable:true
category:1
period:0
lessonid:
maxpoints:100
minpoints:0
weight:100
extracredit:false
scoreentry:1
gradetable:-1
hasdropbox:false
dropboxtype:none
allowpeerreview:false
peerreviewentry:likertscale
reviewvisibletostudent:true
allowselfreview:false
candrop:true
preventdrop:false
includeinfinalgrade:true
excludefromfinalgrade:false
passingscorerequired:false
zerounscored:false
dualgraded:false
masterythreshold:
rubriccolumns:1
peerreviewrubriccolumns:1
visibletostudent:true
visibleintoc:true
gate:false
completiontrigger:1
timetocomplete:1
restrictbymastery:false
defaultquestionscore:
questionsperpage:
timelimit:
attemptlimit:
attemptminimum:
graderule:
securitylevel:
exampassword:
saveandcontinue:false
allowstudentprinting:false
keepparameters:false
randomizequestionorder:false
randomizeanswerorder:false
displayquestions:
displaychoices:
displaypointspossible:
displaycorrectquestions:
displaycorrectchoices:
displayfeedback:
formativeassessment:false
remediationassessment:false
requireanswers:false
forwardnavigation:false
includeformativeingradebook:false
qpcount:
qplocount:
selectbylearningobjectives:false
selectbygroup:false
selectbyquestiontype:false
qpgroups:
qptypes:
homeworkgroups:
alloweditpost:false
allowdeletepost:false
nonthreadeddiscussion:false
allownewthreads:false
groupsetid:-1
surveyprovider:
surveylink:
surveyuser:
surveyname1:
surveyname2:
surveyname3:
surveyname4:
surveyname5:
surveyvalue1:
surveyvalue2:
surveyvalue3:
surveyvalue4:
surveyvalue5:
changes:[object Object]
id:V3ZOY
entityid:~
contentDirty:true
